import chip.Chip;
import chip.ChipRequest;
import chip.connection.Connection;
import chip.layer.Layer;
import chip.module.Filter;
import chip.module.Module;
import chip.module.Orientation;
import chip.pin.Pin;
import gurobi.GRBException;

import java.util.ArrayList;
import java.util.List;

import static chip.module.Orientation.D0;

public class Main {
    public static void main(String[] args) throws GRBException {
        Chip chip = new Chip();
        chip.setHeight(100);
        chip.setWidth(100);
        chip.setzHeight(100);
        List<Layer> layers = new ArrayList<Layer>();
        Layer l0 = new Layer(0);
        Layer l1 = new Layer(1);
        layers.add(l0);
        layers.add(l1);
        chip.setLayers(layers);
        Module m1 = new Filter("m1", 10 , 20);
        Module m2 = new Filter("m2", 20, 16);
        Module m3 = new Filter("m3", 30,30);
        Pin p1 = new Pin(10,0);
        Pin p2 = new Pin(0,15);
        Pin p3 = new Pin(8,0);
        Pin p4 = new Pin(0,6);
        Pin p5 = new Pin(3,0);
        Pin p6 = new Pin(0,30);
        m1.setLayer(l0);
        m1.setX(15);
        m1.setY(15);
        m1.setOrientation(D0);
        m1.addPin(p1);
        m1.addPin(p3);
        m1.addPin(p5);
        p1.setModule(m1);
        p3.setModule(m1);
        p5.setModule(m1);
        m2.setLayer(l0);
        m2.setX(50);
        m2.setY(50);
        m2.setOrientation(D0);
        m2.addPin(p2);
        m2.addPin(p4);
        p2.setModule(m2);
        p4.setModule(m2);
        m3.setLayer(l1);
        m3.setX(40);
        m3.setY(40);
        m3.setOrientation(D0);
        m3.addPin(p6);
        p6.setModule(m3);
        List<Module> modules1 = new ArrayList<Module>();
        List<Module> modules2 = new ArrayList<Module>();
        modules1.add(m1);
        modules1.add(m2);
        modules2.add(m3);
        l0.setModules(modules1);
        l1.setModules(modules2);
        Connection connection1 = new Connection(p1,p2);
        Connection connection2 = new Connection(p3,p4);
        Connection connection3 = new Connection(p5,p6);
        l0.addConnection(connection1);
        l0.addConnection(connection2);
        l1.addConnection(connection3);
        ConnectionChannelSolver ccs = new ConnectionChannelSolver(chip, 10, 3);
        ccs.solve();
        SVGGenerator svg = new SVGGenerator(chip);
        System.out.print(svg.serializeLayer(0));
        System.out.print(svg.serializeLayer(1));
    }
}